package com.capgemini.notification.enums;

public enum NotificationType {
    USER_REGISTERED,
    STARTUP_CREATED,
    STARTUP_REJECTED,
    INVESTMENT_CREATED,
    INVESTMENT_APPROVED,
    INVESTMENT_REJECTED,
    STARTUP_APPROVED,
    TEAM_INVITE_SENT,
    TEAM_INVITE_ACCEPTED,
    TEAM_INVITE_REJECTED,
    PAYMENT_SUCCESS,
    PAYMENT_REJECTED
}
